# Generated by Django 5.1.4 on 2024-12-20 12:34

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginRegister', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeaccount',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=0, max_length=128, region=None),
            preserve_default=False,
        ),
    ]
