# Generated by Django 5.1.2 on 2024-11-04 14:27

import LoginRegister.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginRegister', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('objects', LoginRegister.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='otp',
            field=models.CharField(blank=True, default=None, max_length=6, null=True),
        ),
    ]
