# Generated by Django 5.1.3 on 2024-12-16 11:33

import Promotion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='promotion_img/')),
                ('discount', models.FloatField(validators=[Promotion.models.validate_discount])),
            ],
        ),
    ]
