# Generated by Django 5.1.4 on 2024-12-27 14:15

import Promotion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='promotion_img/')),
                ('discount', models.IntegerField(validators=[Promotion.models.validate_discount])),
                ('type', models.CharField(choices=[('KMTV', 'Khuyen mai thanh vien'), ('KMT', 'Khuyen mai thuong')], max_length=10)),
            ],
        ),
    ]
