# Generated by Django 5.1.4 on 2024-12-24 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_orderitem_status_alter_reservation_status'),
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='menu_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_item', to='Menu.menuitem'),
        ),
    ]
