# Generated by Django 5.1.4 on 2024-12-24 17:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_alter_orderitem_menu_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='server_point',
            new_name='serve_point',
        ),
        migrations.AddField(
            model_name='feedback',
            name='overall_point',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
