# Generated by Django 5.1.4 on 2024-12-24 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0004_rename_server_point_feedback_serve_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='overall_point',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
